### ISSUE TITLE
listing a stall

### ISSUE THREAD

**Issue by MariaRomero** [MariaRomero/streetFood#3]
As as trader
So that I can tell advertise my business
I want to list my stall

**Comment by RobinHeathcote** [comment]
HI Maria!!!

**Comment by MariaRomero** [comment]
hi! :)

On Mon, Jun 6, 2016 at 6:03 PM, Robin Heathcote <notifications@github.com>
wrote:

> HI Maria!!!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MariaRomero/streetFood/issues/3#issuecomment-224021276>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APJ5ylMVT22zZJkqQgyim9HJ-A9Gcqwsks5qJFLOgaJpZM4IvDy7>
> .
>



-- 
Maria Romero
